version: '3'
services:
  node:
    # Faz o docker construir (build) de uma imagem personalizada baseada no arquivo Dockerfile
    build: 
      dockerfile: ./Dockerfile
      context: .
    # Nome do container para facilitar execução
    container_name: trybecash_api
    # Restarta a imagem caso algo a faça parar
    restart: always
    # Diretório padrão de execução
    working_dir: /app
    # Lista de volumes (diretórios) mapeados de fora para dentro do container
    volumes:
      # Monta o diretório atual, com todos os dados da aplicação, dentro do diretório /app
      - ./:/app
    ports:
      # Expõe a porta padrão da aplicação: altere aqui caso use outra porta; na notação porta_de_fora:porta_de_dentro
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    # Informa ao docker, para que o container node seja iniciado após o container database
    depends_on:
      - "database"

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      # Essa variável define a senha do usuário root do MySQL (será a senha que utilizaremos para acessar o MySQL)
      MYSQL_ROOT_PASSWORD: root
      # Essa variável define o nome do banco de dados que será criado ao iniciar MySQL, caso ele não exista.
      MYSQL_DATABASE: trybecashdb
    ports:
      - "33060:3306"
    volumes:
      - ./trybecash_script.sql:/docker-entrypoint-initdb.d/trybecash_script.sql